### ISSUE TITLE
Add licensing to download and KSP Forums thread

### ISSUE THREAD

**Issue by sumghai** [Lilithvia/AzeriteSystemsMods#22]
KSP Forums Moderator @sumghai here.

In keeping with the official [Add-on Posting Rules](https://forum.kerbalspaceprogram.com/index.php?/topic/154851-add-on-posting-rules-november-24-2017/), please ensure that you:

- Include a license file in the downloadable zip (it currently doesn't)
- Identify the license wherever you make it available for download (e.g. in the first post of your thread on the KSP Forums - it currently doesn't).

Please note that non-compliance would result in your download links being removed from the KSP Forums.

Thank you for your understanding.

**Comment by Lilithvia** [comment]
I will get on it ASAP

**Comment by Lilithvia** [comment]
May require a ticket to Blizzard Entertainment, however.

**Comment by Lilithvia** [comment]
2.1.8 will include lincensing.

**Comment by Lilithvia** [comment]
Ticket opened, waiting on reply from Blizz concerning licensing.

**Comment by Lilithvia** [comment]
Issues are fixed.
