### ISSUE TITLE
Blizzard licensing present in repo, but missing from actual downloads

### ISSUE THREAD

**Issue by sumghai** [Lilithvia/AzeriteSystemsMods#35]
@Lilithvia, I'm here again to follow up on the licensing issues for Azerite Systems.

* ✓ Your forum thread clearly states you have obtained permission from Blizzard Entertainment
* ✓ The license file in your publicly-accessible GitHub repo also includes a statement regarding permission from Blizzard, as well as a warning that Blizzard may revoke the agreement at any time.
* ✗ The license file in your actual download on GitHub for the v2.1.8A Alpha release does not mention Blizzard Entertainment in any way
* ✗ The license file in your actual download on CurseForge for the v2.1.8A Alpha release does not mention Blizzard Entertainment in any way

Could you please rectify the last two issues as soon as possible?

I understand licensing is a very frustrating process for you, but at the end of the day, we're just trying to protect the legal interests of everyone involved (you, the KSP user community, SQUAD, Take Two and Blizzard).

**Comment by Lilithvia** [comment]
I've been meaning to push out 2.1.8B, which covers the last two issues.

**Comment by Lilithvia** [comment]
I can push out 2.1.8B right now (which will include the licensing changes), but won't include all the planned things for the release, and might accidentally push unfinished content which I doubt Blizzard will be happy to see made it to our version of "live", that being the latest release.

**Comment by Lilithvia** [comment]
Also, what does Take - Two have to do with anything? That don't own any of the licensing for KSP - as far as I'm aware - Squad does.

**Comment by sumghai** [comment]
Take-Two Interactive acquired KSP from SQUAD, and now publishes it under their own ~~Platoon~~ Private Division indie game label. Therefore, Take-Two now owns the IP for Kerbal Space Program, along with the associated legal obligations.

**Comment by AmberCronin** [comment]
Hey Sumghai, just checking, do you mean Private division, or did something change? In any case, thanks for giving us the heads up!

**Comment by Lilithvia** [comment]
While I'm interested in the point Benjamin brought up, I'd also like to mention a incomplete 2.1.8B build was pushed out to hotfix the licensing issues.

**Comment by sumghai** [comment]
Yes, I meant Private Division.

I've checked your downloads on GitHub and CurseForge, and confirm that the licensing issues have been rectified.

Thank you for your compliance.

**Comment by Lilithvia** [comment]
@sumghai just for a final followup before closing this now rectified issue, I am requesting squad remove all posts concerning the mod needing licensing on our KSPF page, as it's nothing but bad PR.

**Comment by sumghai** [comment]
@Lilithvia 

After consultation with senior moderation staff and administrators, we have decided those posts will not be removed, as they do not violate any forum rules.

They are also useful informational posts to the community regarding correct licensing procedures, so there is a benefit to leaving them there as well.

**Comment by Lilithvia** [comment]
Now you have gone too far. Make your own sticky about correct licensing procedures, don't litter our forum post with it. Or, I will have the OP deleted/locked, and simply repost the thread without them. Your choice.

**Comment by 0111narwhalz** [comment]
Dude, you need to chill.
There's little precedent for the moderators removing copyright warning posts from mod threads—even I have such a post on one of my threads. If you want to contest the presence of these posts on your threads, you are in effect contesting the policy, and this is not the place to contest policy.
In addition, there actually _is_ [a sticky on the subject](https://forum.kerbalspaceprogram.com/index.php?/topic/154851-add-on-posting-rules-november-24-2017/). 1.1 in that post states: "[…] You must also comply with the license terms of each and every external work in your download and **include those licenses in your package.** […]"

**Comment by TotallyNotHuman** [comment]
How exactly has sumghai, a _member of the moderation team, might I add_, gone too far on moderating your thread on a forum they are _supposed_ to moderate?

I'll cut to the chase: you sound awfully pompous for a modder—who, might I add, isn't even making things from scratch—for a video game. Take it down a notch or eleven.

**Comment by Lilithvia** [comment]
You clearly have not paid attention to our development TNH.
Oh wait, that's right, you spammed our discord and were rightfully banned as a result.

**Comment by Lilithvia** [comment]
IF you had access, you would see I am currently working on ISRU models and models for our Atrium parts.
